### ISSUE TITLE
Could you please give some examples?

### ISSUE THREAD

**Issue by Linkfufu** [WheheoHu/pybmd#4]
Hi, thanks for your work! I'm know to python and Davinci resolve, I want to use python to "control" Davinci resolve.
I was wondering could you please give some examples on how to use the pybmd?
For example, can we use pybmd to add to clip next to the previous one and then set it's length to 5 seconds.

**Comment by WheheoHu** [comment]
here is a sample for grab still at marker position use pybmd :[grab_marker_still](https://github.com/WheheoHu/Grab_Stills/blob/main/grab_marker_still.py)

For your purpose , davinci resolve does not support inserting clips into the timeline for now, but you can use the `append_to_timeline` method in the `MediaPool` class (located in media_pool.py) to append clips at the end of the timeline.

**Comment by LittleTerry** [comment]
ok, thanks for your info. Another question is, can we trim the clips using pybmd?

**Comment by WheheoHu** [comment]
> ok, thanks for your info. Another question is, can we trim the clips using pybmd?

I'm afraid this won't do what you need for now.

**Comment by WheheoHu** [comment]
sample at [Samples](https://wheheohu.github.io/pybmd/samples.html)
