### ISSUE TITLE
All Resolve API methods supported?

### ISSUE THREAD

**Issue by donolsch** [WheheoHu/pybmd#5]
Hi there,

That's a pretty cool library! I was wondering if it supports all native DaVinci Resolve methods as per the DaVinci Resolve API documentation or does it just support the ones you're adding?
The reason I'm asking is because I was using the library pydavinci for a while now which provides custom wrappers for Resolve functions. However, the developer does not support/update the library anymore so I'm kinda stuck with whatever functions he included so far.

What I'm looking for is a library that takes care of setting up the initial DaVinci Resolve object including env variables, starting resolve if it's not yet running, etc. But I then want to be able to use all native Resolve API functions.

Is this supported by your library?

Thank you

**Comment by WheheoHu** [comment]
The lib support all native function provided by resolve(Update to 18.6.4),additional functions are located at utility module

**Comment by donolsch** [comment]
Thanks for your quick response. Can you elaborate further on this? I mean, will I be able to use the latest Resolve API functions in the future if at one point you don't decide to update the library. This is essentially what happened to pydavinci. How can I access the new native Resolve API functions if not supported by your library.

Thank you

**Comment by WheheoHu** [comment]
> Thanks for your quick response. Can you elaborate further on this? I mean, will I be able to use the latest Resolve API functions in the future if at one point you don't decide to update the library. This is essentially what happened to pydavinci. How can I access the new native Resolve API functions if not supported by your library?
> 
> 
> 
> Thank you

PR is welcomed.
the library almost is a wrapper for resolve api,if this library does not support the function you want to use,raise an issue or PR,I will solve as soon as I can
